#!/bin/bash

BASH_SEND_SAMP_STATUS=0
BASH_SEND_PAWNCC_STATUS=0

function send_samp_linux()
{
    echo "Do you want to continue downloading SA-MP? (Yy/Nn)"
    read -r -p ">> " SEL_C
    if [[ "$SEL_C" =~ ^[Yy]$ ]]; then
        cd "$BASH_DIR" || bash_end ""
        echo "Select the SA-MP version to download:"
        echo "[A/a] SA-MP 0.3.7 R2-1-1"
        echo "[B/b] SA-MP 0.3.7 R3"
        echo "[C/c] SA-MP 0.3.DL R1"
        read -r -p ">> " _VERSION_
        
        while true; do
            case "$_VERSION_" in
                [Aa])
                    DOWNLOAD_URL_CURL="https://files.sa-mp.app/samp037svr_R2-2-1.tar.gz"
                    DOWNLOAD_FILE_CURL="samp037svr_R2-2-1.tar.gz"
                    break
                    ;;
                [Bb])
                    DOWNLOAD_URL_CURL="https://files.sa-mp.app/samp037svr_R3.tar.gz"
                    DOWNLOAD_FILE_CURL="samp037svr_R3.tar.gz"
                    break
                    ;;
                [Cc])
                    DOWNLOAD_URL_CURL="https://sa-mp.co.id/files/samp03DLsvr_R1.tar.gz"
                    DOWNLOAD_FILE_CURL="samp03DLsvr_R1.tar.gz"
                    break
                    ;;
                *)
                    echo -n "$(bash_coltext_r "E: ")"
                    echo "Invalid selection. Please enter A, B, or C."
                    read -r -p ">> " _VERSION_
                    ;;
            esac
        done

        echo -e "\nDownloading: $DOWNLOAD_URL_CURL -> $DOWNLOAD_FILE_CURL"
        if ! curl -L --progress-bar -o "$DOWNLOAD_FILE_CURL" "$DOWNLOAD_URL_CURL"; then
            echo -n "$(bash_coltext_r "fail: ")"
            echo "Failed to download the file.."
            
            if [ $BASH_SEND_SAMP_STATUS == 1 ]; then
                bash_servers
            elif [ $BASH_SEND_SAMP_STATUS == 2 ]; then
                bash_debug
            elif [ $BASH_SEND_SAMP_STATUS == 0 ]; then
                bash_end ""
            fi
        else
            tar -xzvf "$DOWNLOAD_FILE_CURL" -C "$BASH_DIR" --strip-components=1

            echo
            echo -n "$(bash_coltext_y "Download completed successfully.")"
            echo
            echo "Please rename \"rcon_password\" before running this command again"

            if [ $BASH_SEND_SAMP_STATUS == 1 ]; then
                bash_servers
            elif [ $BASH_SEND_SAMP_STATUS == 2 ]; then
                bash_debug
            elif [ $BASH_SEND_SAMP_STATUS == 0 ]; then
                bash_end ""
            fi
        fi
    else
        if [ $BASH_SEND_SAMP_STATUS == 1 ]; then
            bash_servers
        elif [ $BASH_SEND_SAMP_STATUS == 2 ]; then
            bash_debug
        elif [ $BASH_SEND_SAMP_STATUS == 0 ]; then
            bash_end ""
        fi
    fi
}

function send_compilers_linux()
{
    echo "Do you want to continue downloading PawnCC? (Yy/Nn)"
    read -r -p ">> " SEL_C
    if [[ "$SEL_C" =~ ^[Yy]$ ]]; then
        cd "$BASH_DIR" || bash_end ""
        echo "Select the PawnCC version to download:"
        echo "[A/a] PawnCC 3.10.10"
        echo "[B/b] PawnCC 3.10.9"
        echo "[C/c] PawnCC 3.10.8"
        echo "[D/d] PawnCC 3.10.7"
        echo "[E/e] PawnCC 3.10.6"
        echo "[F/f] PawnCC 3.10.5"
        echo "[G/g] PawnCC 3.10.4"
        read -r -p ">> " _VERSION_

        while true; do
            case "$_VERSION_" in
                [Aa])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.10-linux.tar.gz"
                    break
                    ;;
                [Bb])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.9/pawnc-3.10.9-linux.tar.gz"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.9-linux.tar.gz"
                    break
                    ;;
                [Cc])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.8/pawnc-3.10.8-linux.tar.gz"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.8-linux.tar.gz"
                    break
                    ;;
                [Dd])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.7/pawnc-3.10.7-linux.tar.gz"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.7-linux.tar.gz"
                    break
                    ;;
                [Ee])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.6/pawnc-3.10.6-linux.tar.gz"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.6-linux.tar.gz"
                    break
                    ;;
                [Ff])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.5/pawnc-3.10.5-linux.tar.gz"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.5-linux.tar.gz"
                    break
                    ;;
                [Gg])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.4/pawnc-3.10.4-linux.tar.gz"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.4-linux.tar.gz"
                    break
                    ;;
                *)
                    echo -n "$(bash_coltext_r "E: ")"
                    echo "Invalid selection. Please enter A, B, C, D, or E, F, G."
                    read -r -p ">> " _VERSION_
                    ;;
            esac
        done

        echo -e "\nDownloading: $DOWNLOAD_URL_CURL -> $DOWNLOAD_FILE_CURL"
        if ! curl -L --progress-bar -o "$DOWNLOAD_FILE_CURL" "$DOWNLOAD_URL_CURL"; then
            echo -n "$(bash_coltext_r "fail: ")"
            echo "Failed to download the file.."

            if [ $BASH_SEND_PAWNCC_STATUS == 1 ]; then
                bash_compilers
            elif [ $BASH_SEND_PAWNCC_STATUS == 0 ]; then
                bash_end ""
            fi
        else
            tar -xzvf "$DOWNLOAD_FILE_CURL" -C "$BASH_DIR" --strip-components=1

            echo
            echo -n "$(bash_coltext_y "Download completed successfully.")"
            echo

            if [ $BASH_SEND_PAWNCC_STATUS == 1 ]; then
                bash_compilers
            elif [ $BASH_SEND_PAWNCC_STATUS == 0 ]; then
                bash_end ""
            fi
        fi
    else
        if [ $BASH_SEND_PAWNCC_STATUS == 1 ]; then
            bash_compilers
        elif [ $BASH_SEND_PAWNCC_STATUS == 0 ]; then
            bash_end ""
        fi
    fi
}

function send_samp_win()
{
    echo "Do you want to continue downloading SA-MP? (Yy/Nn)"
    read -r -p ">> " SEL_C
    if [[ "$SEL_C" =~ ^[Yy]$ ]]; then
        cd "$BASH_DIR" || bash_end ""
        echo "Select the SA-MP version to download:"
        echo "[A/a] SA-MP 0.3.7 R2-1-1"
        echo "[B/b] SA-MP 0.3.7 R3"
        echo "[C/c] SA-MP 0.3.DL R1"
        read -r -p ">> " _VERSION_

        while true; do
            case "$_VERSION_" in
                [Aa])
                    DOWNLOAD_URL_CURL="https://files.sa-mp.app/samp037_svr_R2-1-1_win32.zip"
                    DOWNLOAD_FILE_CURL="samp037_svr_R2-1-1_win32.zip"
                    break
                    ;;
                [Bb])
                    DOWNLOAD_URL_CURL="https://files.sa-mp.app/samp037_svr_R3_win32.zip"
                    DOWNLOAD_FILE_CURL="samp037_svr_R3_win32.zip"
                    break
                    ;;
                [Cc])
                    DOWNLOAD_URL_CURL="https://sa-mp.co.id/files/samp03DL_svr_R1_win32.zip"
                    DOWNLOAD_FILE_CURL="samp03DL_svr_R1_win32.zip"
                    break
                    ;;
                *)
                    echo -n "$(bash_coltext_r "E: ")"
                    echo "Invalid selection. Please enter A, B, or C."
                    read -r -p ">> " _VERSION_
                    ;;
            esac
        done

        echo -e "\nDownloading: $DOWNLOAD_URL_CURL -> $DOWNLOAD_FILE_CURL"
        if ! curl -L --progress-bar -o "$DOWNLOAD_FILE_CURL" "$DOWNLOAD_URL_CURL"; then
            echo -n "$(bash_coltext_r "fail: ")"
            echo "Failed to download the file.."

            if [ $BASH_SEND_SAMP_STATUS == 1 ]; then
                bash_servers
            elif [ $BASH_SEND_SAMP_STATUS == 2 ]; then
                bash_debug
            elif [ $BASH_SEND_SAMP_STATUS == 0 ]; then
                bash_end ""
            fi
        else
            unzip -q "$DOWNLOAD_FILE_CURL" -d "$BASH_DIR"

            echo
            echo -n "$(bash_coltext_y "Download completed successfully.")"
            echo
            echo "Please rename \"rcon_password\" before running this command again"

            if [ $BASH_SEND_SAMP_STATUS == 1 ]; then
                bash_servers
            elif [ $BASH_SEND_SAMP_STATUS == 2 ]; then
                bash_debug
            elif [ $BASH_SEND_SAMP_STATUS == 0 ]; then
                bash_end ""
            fi
        fi
    else
        if [ $BASH_SEND_SAMP_STATUS == 1 ]; then
            bash_servers
        elif [ $BASH_SEND_SAMP_STATUS == 2 ]; then
            bash_debug
        elif [ $BASH_SEND_SAMP_STATUS == 0 ]; then
            bash_end ""
        fi
    fi
}

function send_compilers_win()
{
    echo "Do you want to continue downloading PawnCC? (Yy/Nn)"
    read -r -p ">> " SEL_C
    if [[ "$SEL_C" =~ ^[Yy]$ ]]; then
        cd "$BASH_DIR" || bash_end ""
        echo "Select the PawnCC version to download:"
        echo "[A/a] PawnCC 3.10.10"
        echo "[B/b] PawnCC 3.10.9"
        echo "[C/c] PawnCC 3.10.8"
        echo "[D/d] PawnCC 3.10.7"
        echo "[E/e] PawnCC 3.10.6"
        echo "[F/f] PawnCC 3.10.5"
        echo "[G/g] PawnCC 3.10.4"
        read -r -p ">> " _VERSION_

        while true; do
            case "$_VERSION_" in
                [Aa])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-windows.zip"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.10-windows.zip"
                    break
                    ;;
                [Bb])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.9/pawnc-3.10.9-windows.zip"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.9-windows.zip"
                    break
                    ;;
                [Cc])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.8/pawnc-3.10.8-windows.zip"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.8-windows.zip"
                    break
                    ;;
                [Dd])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.7/pawnc-3.10.7-windows.zip"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.7-windows.zip"
                    break
                    ;;
                [Ee])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.6/pawnc-3.10.6-windows.zip"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.6-windows.zip"
                    break
                    ;;
                [Ff])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.5/pawnc-3.10.5-windows.zip"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.5-windows.zip"
                    break
                    ;;
                [Gg])
                    DOWNLOAD_URL_CURL="https://github.com/pawn-lang/compiler/releases/download/v3.10.4/pawnc-3.10.4-windows.zip"
                    DOWNLOAD_FILE_CURL="pawnc-3.10.4-windows.zip"
                    break
                    ;;
                *)
                    echo -n "$(bash_coltext_r "E: ")"
                    echo "Invalid selection. Please enter A, B, C, D, or E, F, G."
                    read -r -p ">> " _VERSION_
                    ;;
            esac
        done

        echo -e "\nDownloading: $DOWNLOAD_URL_CURL -> $DOWNLOAD_FILE_CURL"
        if ! curl -L --progress-bar -o "$DOWNLOAD_FILE_CURL" "$DOWNLOAD_URL_CURL"; then
            echo -n "$(bash_coltext_r "fail: ")"
            echo "Failed to download the file.."

            if [ $BASH_SEND_PAWNCC_STATUS == 1 ]; then
                bash_compilers
            elif [ $BASH_SEND_PAWNCC_STATUS == 0 ]; then
                bash_end ""
            fi
        else
            unzip -q "$DOWNLOAD_FILE_CURL" -d "$BASH_DIR"

            echo
            echo -n "$(bash_coltext_y "Download completed successfully.")"
            echo

            if [ $BASH_SEND_PAWNCC_STATUS == 1 ]; then
                bash_compilers
            elif [ $BASH_SEND_PAWNCC_STATUS == 0 ]; then
                bash_end ""
            fi
        fi
    else
        if [ $BASH_SEND_PAWNCC_STATUS == 1 ]; then
            bash_compilers
        elif [ $BASH_SEND_PAWNCC_STATUS == 0 ]; then
            bash_end ""
        fi
    fi
}