#!/bin/bash

if [ ! -f "data.json" ]; then
    cat > data.json <<EOF
{
    "amx_opt": "-d0",
    "allow_subdir": "/pawno/include",

    "ppm_dir": "pawno",
    "ppm_subdir": "include",
    "ppm_type": "urllib3",

    "chatbot_token": "",
    "chatbot_model": "",
    "chatbot_biodata": "",
    "chatbot_json_get": ""
}
EOF
fi

##################################################################
AMX_OPT_F=$(grep '"amx_opt"' data.json | sed -E 's/.*"amx_opt": "(.*)".*/\1/')
##################################################################

# @pawn-lang compiler 3.10.7^ - ("https://github.com/pawn-lang/compiler")

# Usage:   pawncc <filename> [filename...] [options]
# Options:
#        -A<num>  alignment in bytes of the data segment and the stack
#        -a       output assembler code
#        -C[+/-]  compact encoding for output file (default=+)
#        -c<name> codepage name or number; e.g. 1252 for Windows Latin-1
#        -Dpath   active directory path
#        -d<num>  debuging level (default=-d1)
#            0    no symbolic information, no run-time checks
#            1    run-time checks, no symbolic information
#            2    full debug information and dynamic checking
#            3    same as -d2, but implies -O0
#        -e<name> set name of error file (quiet compile)
#        -H<hwnd> window handle to send a notification message on finish
#        -i<name> path for include files
#        -l       create list file (preprocess only)
#        -o<name> set base name of (P-code) output file
#        -O<num>  optimization level (default=-O1)
#            0    no optimization
#            1    JIT-compatible optimizations only
#            2    full optimizations
#        -p<name> set name of "prefix" file
#        -R[+/-]  add detailed recursion report with call chains (default=-)
#        -r[name] write cross reference report to console or to specified file
#        -S<num>  stack/heap size in cells (default=4096)
#        -s<num>  skip lines from the input file
#        -t<num>  TAB indent size (in character positions, default=8)
#        -v<num>  verbosity level; 0=quiet, 1=normal, 2=verbose (default=1)
#        -w<num>  disable a specific warning by its number
#        -X<num>  abstract machine size limit in bytes
#        -XD<num> abstract machine data/stack size limit in bytes
#        -Z[+/-]  run in compatibility mode (default=-)
#        -E[+/-]  turn warnings in to errors
#        -\       use '\' for escape characters
#        -^       use '^' for escape characters
#        -;[+/-]  require a semicolon to end each statement (default=-)
#        -([+/-]  require parantheses for function invocation (default=-)
#        sym=val  define constant "sym" with value "val"
#        sym=     define constant "sym" with value 0

if [ ! -d .cache ]; then
    mkdir .cache
fi

_DIR1=$(awk -F'"' '/"ppm_dir"/ {print $4}' data.json)
_DIR2=$(awk -F'"' '/"ppm_subdir"/ {print $4}' data.json)

METADAT_FILE=".cache/compiler.log"

SHUSERS="$USER@$(hostname 2>/dev/null || echo )"

BASH_DIR="$(dirname "$0")"
BASH_TITLE=""
BASH_NAME="pawnclis"
BASH_SERVER="samp03svr"

BASH_BUILD="2025-03-08"

PAWNCCS="pawncc"

BASH_ALLOW_SDIR=$(grep '"allow_subdir"' data.json | sed -E 's/.*"allow_subdir": "(.*)".*/\1/')

COMPILER_MODE=false
BASH_SEND_SAMP_STATUS=0
BASH_SEND_PAWNCC_STATUS=0
COMPILER_PAWNCC=""

VAR_NOTICE=0

# "https://groq.com/"
CHATBOT_TOKEN=$(grep '"chatbot_token"' data.json | sed -E 's/.*"chatbot_token": "(.*)".*/\1/')
CHATBOT_MODEL=$(grep '"chatbot_model"' data.json | sed -E 's/.*"chatbot_model": "(.*)".*/\1/')
CHATBOT_BIODATA=$(grep '"chatbot_biodata"' data.json | sed -E 's/.*"chatbot_biodata": "(.*)".*/\1/')
CHATBOT_JSON_GET=$(grep '"chatbot_json_get"' data.json | sed -E 's/.*"chatbot_json_get": "(.*)".*/\1/')
    # "python3"
    # "sed"
    # "jq"
    # "grep"

URL_DOWNLOAD="https://raw.githubusercontent.com/vilksons/pawnclis/refs/heads/main/Scripts/$BASH_NAME"

bash_title() {
    echo -ne "\033]0;$1\007"
}

bash_title "$SHUSERS:~"

COLOR_Y="\e[33m"
COLOR_G="\e[32m"
COLOR_R="\e[91m"

function bash_coltext_y() {
    local color="$COLOR_Y"
    local text="$1"
    echo -e "${color}${text}\e[0m"
}

function bash_coltext_g() {
    local color="$COLOR_G"
    local text="$1"
    echo -e "${color}${text}\e[0m"
}

function bash_coltext_r() {
    local color="$COLOR_R"
    local text="$1"
    echo -e "${color}${text}\e[0m"
}

# shellcheck source=/dev/null

function bash_typeof() {
    if [[ $VAR_NOTICE != 1 ]]; then
        VAR_NOTICE=1
        
        GITHUB_URL="https://api.github.com/repos/vilksons/pawnclis/contents/Version"
        LATEST_VERSION=$(curl -s "$GITHUB_URL" | grep '"name":' | awk -F'"' '{print $4}' | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' | sort -r | head -n 1)

        if [[ ! "$LATEST_VERSION" == "$BASH_BUILD" ]]; then
            echo "The latest version is here: $LATEST_VERSION. Your current version: $BASH_BUILD..!."
        fi

        if [ ! -d .lib ]; then
            mkdir .lib
        fi

        if [ -f "$BASH_DIR/.lib/libppm" ]; then
            source "$BASH_DIR/.lib/libppm"
        else
            cd "$BASH_DIR/.lib" || echo ""

            curl -L --progress-bar -o "libppm" "https://raw.githubusercontent.com/vilksons/pawnclis/refs/heads/main/Scripts/.lib/libppm"

            sleep 0
            cd "$BASH_DIR" || echo ""

            clear

            if [ -f "$BASH_DIR/.lib/libpawnclis" ]; then
                source "$BASH_DIR/.lib/libpawnclis"
            else
                cd "$BASH_DIR/.lib" || echo ""

                curl -L --progress-bar -o "libpawnclis" "https://raw.githubusercontent.com/vilksons/pawnclis/refs/heads/main/Scripts/.lib/libpawnclis"

                sleep 0

                clear

                cd "$(dirname "$0")" || echo ""

                ./$BASH_NAME ""
            fi
        fi
    fi

    COMPILER_MODE=false

    if [[ "$BASH_SEND_SAMP_STATUS" != 0 ]]; then
        BASH_SEND_SAMP_STATUS=0
    fi
    if [[ "$BASH_SEND_PAWNCC_STATUS" != 0 ]]; then
        BASH_SEND_PAWNCC_STATUS=0
    fi
    
    COMPILER_PAWNCC=""

    BASH_TITLE="Paw Mode"
    bash_title "$SHUSERS:~/$BASH_TITLE"

    echo -n "$(bash_coltext_y "$SHUSERS")"
    echo -n ":~$ "
    read -r OPBASH_F
    bash_next
}

bash_next() {
    local BASH_OPTION="paw"

    case "$OPBASH_F" in
        "$BASH_OPTION -c"* | "compiles"*)
            BASH_TITLE="compilator"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            killall -15 "samp03svr" >/dev/null 2>&1
            
            if [[ "$OPBASH_F" =~ ^"$BASH_OPTION -c compiler " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -c compiler "}"
            elif [[ "$OPBASH_F" =~ ^"$BASH_OPTION -c " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -c "}"
            else
                COMPILER_MODE=true
                bash_compilers
            fi

            while IFS= read -r -d '' pawncc; do
                if [ -f "$pawncc" ]; then
                    COMPILER_PAWNCC="$pawncc"
                    break
                fi
            done < <(find "$BASH_DIR" -type f -iname "$PAWNCCS" -print0)

            if [ -z "$COMPILER_PAWNCC" ]; then
                echo "# pawncc not found.."
                echo
                BASH_SEND_PAWNCC_STATUS=1
                send_compilers_linux
            fi

            mapfile -d '' files < <(find "$BASH_DIR" -name "*$FOR_FIND_INPUT*" -type f -print0)

            for file in "${files[@]}"; do
                if [ -f "$file" ] && [[ "$file" != *.amx ]]; then
                    bash_title "$file"

                    AMX_O="$(dirname "$file")/$(basename "${file%.*}.amx")"

                    echo -n "$(bash_coltext_y "info: ")"
                    echo "Processing: $file"

                    "$COMPILER_PAWNCC" -i"$BASH_DIR$BASH_ALLOW_SDIR" "$file" -o"$AMX_O" "$AMX_OPT_F" > "$METADAT_FILE" 2>&1
                    EXIT_STATUS=$?

                    if [ $EXIT_STATUS -ne 0 ] || grep -q "fatal error" "$METADAT_FILE"; then
                        echo "Compilation failed with exit code: $EXIT_STATUS"
                        [ -f "$AMX_O" ] && rm -rf "$AMX_O"
                    fi

                    _cache_compiler
                    sleep 0
                    cat "$METADAT_FILE"

                    if [ -s "$AMX_O" ]; then
                        echo
                        echo "~ $AMX_O"
                        if [ "$COMPILER_MODE" == "true" ]; then
                            BASH_TITLE="compilers"
                            bash_title "$SHUSERS:~/ $BASH_TITLE"
                        elif [ "$COMPILER_MODE" == "false" ]; then
                            BASH_TITLE="compiler - running"
                            bash_title "$SHUSERS:~/ $BASH_TITLE"
                        fi
                        echo "total size : $(stat -c%s "$AMX_O") bytes"
                        echo
                    else
                        if [ "$COMPILER_MODE" == "false" ]; then
                            bash_end ""
                        fi
                    fi
                fi
            done

            killall -15 "samp03svr" >/dev/null 2>&1
            bash_end ""

            echo
            ;;
        "$BASH_OPTION -r"* | "running"*)
            BASH_TITLE="running"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            killall -15 "samp03svr" >/dev/null 2>&1

            if [[ "$OPBASH_F" =~ ^"$BASH_OPTION -r running " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -r running "}"
            elif [[ "$OPBASH_F" =~ ^"$BASH_OPTION -r " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -r "}"
            else
                bash_servers
            fi

            if [ ! -f "server.cfg" ]; then
                echo "server.cfg not found!"
                bash_end ""
            fi

            mv server.cfg server.cfg.bak

            awk -v new_gamemode="$FOR_FIND_INPUT" '
            /^gamemode0 / {$2=new_gamemode} 1' server.cfg.bak > server.cfg

            echo "New server.cfg created with gamemode: $FOR_FIND_INPUT"

            if [ ! -f "$BASH_SERVER" ]; then
                echo
                echo "# $BASH_SERVER not found.."
                BASH_SEND_SAMP_STATUS=2
                send_samp_linux
            else
                chmod 777 "$BASH_SERVER"
                ./samp03svr &
                sleep 1
                cat server_log.txt
                echo
            fi

            rm -f server.cfg
            mv server.cfg.bak server.cfg
            echo "Original server.cfg has been restored."

            bash_end ""
            ;;
        "$BASH_OPTION -d"* | "debug"*)
            BASH_TITLE="debugging a server"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            killall -15 "samp03svr" >/dev/null 2>&1

            if [[ "$OPBASH_F" =~ ^"$BASH_OPTION -d debug " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -d debug "}"
            elif [[ "$OPBASH_F" =~ ^"$BASH_OPTION -d " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -d "}"
            else
                echo -n ":: Enter gamemode name:"
                echo
                read -r -p ">>> " FOR_FIND_INPUT
            fi

            if [ ! -f "server.cfg" ]; then
                echo "server.cfg not found!"
                bash_end ""
            fi

            mv server.cfg server.cfg.bak

            awk -v new_gamemode="$FOR_FIND_INPUT" '
            /^gamemode0 / {$2=new_gamemode} 1' server.cfg.bak > server.cfg

            echo "New server.cfg created with gamemode: $FOR_FIND_INPUT"

            if [ ! -f "$BASH_SERVER" ]; then
                echo
                echo "# $BASH_SERVER not found.."
                BASH_SEND_SAMP_STATUS=2
                send_samp_linux
            else
                chmod 777 "$BASH_SERVER"
                ./samp03svr &
                sleep 1
                cat server_log.txt
                echo
                killall -15 "samp03svr" >/dev/null 2>&1
            fi

            rm -f server.cfg
            mv server.cfg.bak server.cfg
            echo "Original server.cfg has been restored."

            bash_end ""
            ;;
        "$BASH_OPTION -s" | "stop")
            BASH_TITLE="stopped a server"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            killall -15 "samp03svr" >/dev/null 2>&1
            bash_end ""
            ;;
        "$BASH_OPTION -t" | "restart")
            BASH_TITLE="restart a server"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            if pgrep -x "samp03svr" >/dev/null; then
                killall -15 "samp03svr" >/dev/null 2>&1
                sleep 2
                bash_servers
            else
                echo "sa-mp server in running not found."
            fi
            ;;
        "$BASH_OPTION -u" | "compilerunn")
            BASH_TITLE="compile & running"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            killall -15 "samp03svr" >/dev/null 2>&1

            COMPILER_MODE=false

            echo
            compilers
            
            if grep -i "error" "$METADAT_FILE" >/dev/null; then
                echo
            else
                ok_next
            fi
            ;;
        "$BASH_OPTION -g" | "gamemode")
            BASH_TITLE="download gamemode"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            BASH_SEND_SAMP_STATUS=0

            while true; do
                echo "Linux/Windows [a/b]"
                read -r -p ">> " SEL_CO
                case "$SEL_CO" in
                    [Aa])
                        send_samp_linux
                        break
                        ;;
                    [Bb])
                        send_samp_win
                        break
                        ;;
                    *)
                        echo -n "$(bash_coltext_r "E: ")"
                        echo "Invalid selection. Please enter A or B."
                        ;;
                esac
            done

            bash_end ""
            ;;
        "$BASH_OPTION -p" | "pawncc")
            BASH_TITLE="download pawncc"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            BASH_SEND_PAWNCC_STATUS=0

            while true; do
                echo "Linux/Windows [a/b]"
                read -r -p ">> " SEL_CO
                case "$SEL_CO" in
                    [Aa])
                        send_compilers_linux
                        break
                        ;;
                    [Bb])
                        send_compilers_win
                        break
                        ;;
                    *)
                        echo -n "$(bash_coltext_r "E: ")"
                        echo "Invalid selection. Please enter A or B."
                        ;;
                esac
            done

            bash_end ""
            ;;
        "$BASH_OPTION -C" | "clear")
            BASH_TITLE="clear screen"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            clear; echo -ne "\033[3J"

            bash_typeof ""
            ;;
        "$BASH_OPTION -V" | "tasks")
            BASH_TITLE="vscode tasks"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            if [ -d ".vscode" ]; then
                rm -rf .vscode
            fi
            
            mkdir .vscode
            cat <<EOF > .vscode/tasks.json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run PawnCLIS",
      "type": "process",
      "command": "\${workspaceFolder}/$BASH_NAME",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": [],
      "detail": "Task to run the PawnCLIS"
    }
  ]
}
EOF
            echo "OK? '.vscode/tasks.json'...: [yes]"

            bash_end ""
            ;;
        "$BASH_OPTION -F" | "check")
            BASH_TITLE="folder check"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            bash_check_dir "filterscripts"
            bash_check_dir "gamemodes"
            bash_check_dir "scriptfiles"

            if [ -f "server.cfg" ]; then
                echo
                echo "# server.cfg is .. Ok .."
                echo " [A subdirectory or file server.cfg already exists.]"
            else
                cat <<EOF > server.cfg
echo Executing Server Config...
lanmode 0
rcon_password changename
maxplayers 150
port 7777
hostname SA-MP 0.3
gamemode0 main 1
filterscripts
announce 0
chatlogging 0
weburl www.sa-mp.com
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000
maxnpc 0
logtimeformat [%H:%M:%S]
language English
EOF
                echo "OK? '$BASH_DIR/server.cfg'...: [yes]"
                echo
                cat server.cfg
                echo
                bash_end ""
            fi
            ;;
        "$BASH_OPTION -v" | "$BASH_OPTION -version" | "$BASH_OPTION --version" | "version")
            BASH_TITLE="version"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            echo "PawnCLIS Version: $BASH_BUILD"

            bash_end ""
            ;;
        "$BASH_OPTION -T"* | "type"*)
            BASH_TITLE="type files"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            if [[ "$OPBASH_F" =~ ^"$BASH_OPTION -T type " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -T type "}"
            elif [[ "$OPBASH_F" =~ ^"$BASH_OPTION -T " ]]; then
                FOR_FIND_INPUT="${OPBASH_F#"$BASH_OPTION -T "}"
            else 
                echo -n ":: Enter the file name:"
                read -r -p ">>> " FOR_FIND_INPUT
            fi

            cat "$FOR_FIND_INPUT"
            echo

            bash_end ""
            ;;
        "$BASH_OPTION -D" | "directory")
            BASH_TITLE="directory"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            ls -a

            bash_end ""
            ;;
        "$BASH_OPTION -K" | "kill")
            BASH_TITLE="kill"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            sleep 0

            chmod +x $BASH_NAME
            bash ./$BASH_NAME
            ;;
        "$BASH_OPTION -S" | "update" | "sync")
            BASH_TITLE="Update PawnCLIS"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            if [[ "$LATEST_VERSION" == "$BASH_BUILD" ]]; then
                echo "The version is the latest!."
                bash_end
            fi
            
            cd "$BASH_DIR/.lib" || echo ""

            curl -L --progress-bar -o "libppm" "https://raw.githubusercontent.com/vilksons/pawnclis/refs/heads/main/Scripts/.lib/libppm"
            curl -L --progress-bar -o "libpawnclis" "https://raw.githubusercontent.com/vilksons/pawnclis/refs/heads/main/Scripts/.lib/libpawnclis"

            sleep 0
            
            cd "$(dirname "$0")" || echo ""

            curl -L --progress-bar -o "$BASH_NAME" "$URL_DOWNLOAD"

            sleep 1

            clear

            chmod +x $BASH_NAME
            bash ./$BASH_NAME
            ;;
        "$BASH_OPTION -X"* | "checksums"*)
            BASH_TITLE="Checksums"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            local FOR_FIND_ARGS="${OPBASH_F#"$BASH_OPTION -X"}"
            local FOR_FIND_ARGS="${FOR_FIND_ARGS#checksums}"

            cd "$BASH_DIR" || echo ""

            if [[ -n "$FOR_FIND_ARGS" ]]; then
                FOR_FIND_INPUT="$FOR_FIND_ARGS"
            else
                echo "sha1:"
                sha1sum "$BASH_NAME"
                echo "sha256:"
                sha256sum "$BASH_NAME"
                echo "md5:"
                md5sum "$BASH_NAME"
                bash_end ""
            fi

            if [[ "$FOR_FIND_INPUT" == "sha1" ]]; then
                sha1sum "$BASH_NAME"
            elif [[ "$FOR_FIND_INPUT" == "sha256" ]]; then
                sha256sum "$BASH_NAME"
            elif [[ "$FOR_FIND_INPUT" == "md5" ]]; then
                md5sum "$BASH_NAME"
            fi

            bash_end ""
            ;;
        "$BASH_OPTION -W" | "whoami")
            BASH_TITLE="whoami"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            whoami
            bash_end ""
            ;;
        "$BASH_OPTION -e" | "exit")
            BASH_TITLE="exit"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            sleep 0

            bash
            ;;
        "$BASH_OPTION -a"* | "chatbot"*)
            BASH_TITLE="chatbot"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            local FOR_FIND_ARGS="${OPBASH_F#"$BASH_OPTION -a "}"
            local FOR_FIND_ARGS="${FOR_FIND_ARGS#chatbot }"

            if [[ -n "$FOR_FIND_ARGS" ]]; then
                user_question="$FOR_FIND_ARGS"
            else
                echo -n ":: Enter the Question:"
                echo
                echo " -> enter \"exit\" to exit"
                read -r -p ">>> " user_question
            fi

            if [[ "$user_question" == "exit" ]]; then
                bash_end ""
            fi

            echo "*sending..."

            response=$(curl -s -X POST https://api.groq.com/openai/v1/chat/completions \
                -H "Authorization: Bearer $CHATBOT_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{
                    \"model\": \"$CHATBOT_MODEL\",
                    \"messages\": [
                        {
                        \"role\": \"system\",
                        \"content\": \"$CHATBOT_BIODATA\"
                        },
                        {
                        \"role\": \"user\",
                        \"content\": \"$user_question\"
                        }
                    ],
                    \"temperature\": 1,
                    \"max_tokens\": 1024,
                    \"top_p\": 1,
                    \"stream\": false,
                    \"stop\": null
                    }")

            if [ "$CHATBOT_JSON_GET" == "python3" ]; then
                echo "$response" | python3 -c "import sys, json; print(json.load(sys.stdin)['choices'][0]['message']['content'])"
            elif [ "$CHATBOT_JSON_GET" == "sed" ]; then
                echo "$response" | sed -E 's/.*"content":"([^"]*)".*/\1/' | awk '{gsub(/\\n/, "\n")}1'
            elif [ "$CHATBOT_JSON_GET" == "jq" ]; then
                echo "$response" | jq -r '.choices[0].message.content'
            elif [ "$CHATBOT_JSON_GET" == "grep" ]; then
                echo "$response" | grep -oP '"content":"\K[^"]*'
            fi
            
            echo "----------------------------------"
            
            bash_end ""
            ;;
        "$BASH_OPTION -N"* | "nano"*)
            local FOR_FIND_ARGS="${OPBASH_F#"$BASH_OPTION -N "}"
            local FOR_FIND_ARGS="${FOR_FIND_ARGS#nano }"

            BASH_TITLE="GNU Nano Editor"
            echo "$SHUSERS:~/ $BASH_TITLE"

            if [[ -n "$FOR_FIND_ARGS" ]]; then
                FILE_PATH="$FOR_FIND_ARGS"
            else
                echo ":: Enter the File:"
                read -r -p ">>> " FILE_PATH
            fi

            nano "$FILE_PATH"

            bash_end ""
            ;;
        "$BASH_OPTION -O" | "remcac")
            echo -n "Cache Directory: $BASH_DIR/.cache"
            echo 
            read -r -p ":: Do you want to remove ALL files from cache? [Y/N] " PERMISSION_NEED

            while true; do
            case "$PERMISSION_NEED" in
                [Yy])
                    cd "$BASH_DIR" || echo ""
                    rm -rf "$BASH_DIR/.cache"
                    bash_typeof ""
                    break
                    ;;
                *)
                    bash_typeof ""
                    esac
            done
            ;;
        "fetch")
            echo " _____                      _____ _      _____  _____  "
            echo " |  __ \                    / ____| |    |_   _|/ ____| "
            echo " | |__) |_ ___      ___ __ | |    | |      | | | (___   "
            echo " |  ___/ _' \ \ /\ / / '_ \| |    | |      | |  \___ \  "
            echo " | |  | (_| |\ V  V /| | | | |____| |____ _| |_ ____) | "
            echo " |_|   \__,_| \_/\_/ |_| |_|\_____|______|_____|_____/ "
            bash_end
            ;;
        "$BASH_OPTION -M" | "ppm")
            bash_typeof2 ""
            bash_help2 ""
            ;;
        "help")
            BASH_TITLE="help"
            bash_title "$SHUSERS:~/ $BASH_TITLE"

            bash_help
            bash_typeof ""
            ;;
        "$BASH_OPTION")
            bash_help
            bash_typeof ""
            ;;
        "")
            bash_typeof ""
            ;;
        " ")
            bash_typeof ""
            ;;
        *)
            echo "error: $OPBASH_F: command not found"
            bash_typeof ""
            ;;
    esac
}

function bash_help()
{
    echo "Usage: paw <command> [<args>]"
    echo "Commonly used commands can be classified as follows:"
    echo
    echo "    Basic Operations:"
    echo "        compile     (-c) | compiles       Compile a project."
    echo "        running     (-r) | runnning       Check if a process is running."
    echo "        debugging   (-d) | debug          Start a debugging server."
    echo "        stop        (-s) | stop           Stop a server."
    echo "        restart     (-t) | restart        Restart a server"
    echo "        compile-run (-u) | compilerunn    Compile and run a project."
    echo "        download-gm (-g) | gamemode       Download a gamemode."
    echo "        download-pcc(-p) | pawncc         Download pawncc."
    echo "        clear       (-C) | clear          Clear the screen."
    echo "        checksums   (-X) | checksums      Generate or verify checksums."
    echo "        folder-check(-F) | check          Check a folder's integrity."
    echo "        vscode-tasks(-V) | tasks          Generate VSCode tasks."
    echo "        type-file   (-T) | type           Display file type."
    echo "        whoami      (-W) | whoami         Display current user."
    echo "        kill-bash   (-K) | kill           Kill a command."
    echo "        directory   (-D) | directory      Change or display the current directory."
    echo "        version     (-v) | version        Display tool version."
    echo "        update      (-S) | update/sync    Update the tool."
    echo "        exit        (-e) | exit           Exit or start a bash shell."
    echo "        chatbot     (-a) | chatbot        Ask an AI for assistance."
    echo "        GNU Nano    (-N) | nano           GNU/Linux Nano Editor."
    echo "        enter PPM   (-M) | ppm            Enter PawnCLIS Package Manager Mode."
    echo "        remove cache(-O) | remcac         Remove PawnCLIS Cache."
    echo
    echo "    Package Management:"
    echo "        sync        (-S) | install        Synchronize and install/replace packages. (ppm)"
    echo "        remove      (-r) | remove         Remove packages. (ppm)"
    echo "        end         (-E) | end            End PawnCLIS Package Manager Mode. (ppm)"
    echo
}

function bash_help2()
{
    echo "Usage: paw <command> [<args>]"
    echo "Commonly used commands can be classified as follows:"
    echo
    echo "    Package Management:"
    echo "        sync        (-S) | install    Synchronize and install/replace packages. (ppm)"
    echo "        remove      (-r) | remove     Remove packages. (ppm)"
    echo "        end         (-E) | end        End PawnCLIS Package Manager Mode. (ppm)"
    echo
}

function bash_end() {
    echo -n "$(bash_coltext_y "Press any key to return.")"
    echo
    read -r -n 1 -s
    bash_typeof ""
}

function bash_servers() {
    if [ -f "$BASH_DIR/server_log.txt" ]; then
        rm -rf "$BASH_DIR/server_log.txt"
    fi
    if [ ! -f "$BASH_SERVER" ]; then
        echo
        echo "# $BASH_SERVER not found.."
        BASH_SEND_SAMP_STATUS=1
        send_samp_linux
    fi
    chmod 777 $BASH_SERVER
    ./samp03svr &
    sleep 2
    if ! pgrep -x "samp03svr" >/dev/null; then
        BASH_TITLE="running - failed"
        bash_title "$SHUSERS:~/ $BASH_TITLE"
        echo
        echo -n "$(bash_coltext_r "# Fail")"
        echo
        if [ -f "server_log.txt" ]; then
            sleep 2
            cat server_log.txt
            echo
        else
            echo "# server_log.txt not found."
        fi
        echo -n "$(bash_coltext_y "# End.")"
        echo
        bash_typeof ""
    else
        echo
        echo -n "$(bash_coltext_y "# Success")"
        echo
        sleep 2
        if grep -i "error" server_log.txt >/dev/null; then
            start_true
        else
            start_false
        fi
    fi
}

function bash_debug() {
    if [ ! -f "server.cfg" ]; then
        echo "server.cfg not found!"
        bash_end ""
    fi

    mv server.cfg server.cfg.bak

    echo -n ":: Enter gamemode name:"
    echo
    read -r -p ">>> " GAMEMODE_NAME

    awk -v new_gamemode="$GAMEMODE_NAME" '
    /^gamemode0 / {$2=new_gamemode} 1' server.cfg.bak > server.cfg

    echo "New server.cfg created with gamemode: $GAMEMODE_NAME"

    if [ ! -f "$BASH_SERVER" ]; then
        echo
        echo "# $BASH_SERVER not found.."
        BASH_SEND_SAMP_STATUS=2
        send_samp_linux
    else
        chmod 777 "$BASH_SERVER"
        ./samp03svr &
        sleep 1
        cat server_log.txt
        echo
        killall -15 "samp03svr" >/dev/null 2>&1
    fi

    rm -f server.cfg
    mv server.cfg.bak server.cfg
    echo "Original server.cfg has been restored."

    bash_end ""
}

function bash_compilers() {
    SHFILE="false"

    while IFS= read -r -d '' pawncc; do
        if [ -f "$pawncc" ]; then
            COMPILER_PAWNCC="$pawncc"
            break
        fi
    done < <(find "$BASH_DIR" -type f -iname "$PAWNCCS" -print0)

    if [ -z "$COMPILER_PAWNCC" ]; then
        echo "# pawncc not found.."
        echo
        BASH_SEND_PAWNCC_STATUS=1
        send_compilers_linux
    fi

    mapfile -d '' files < <(find "$BASH_DIR" -name "*.io*" -type f -print0)

    for file in "${files[@]}"; do
        if [ -f "$file" ] && [[ "$file" != *.amx ]]; then
            SHFILE="true"
            bash_title "$file"

            AMX_O="$(dirname "$file")/$(basename "${file%.io*}.amx")"

            echo -n "$(bash_coltext_y "info: ")"
            echo "Processing: $file"

            "$COMPILER_PAWNCC" -i"$BASH_DIR$BASH_ALLOW_SDIR" "$file" -o"$AMX_O" "$AMX_OPT_F" > "$METADAT_FILE" 2>&1
            EXIT_STATUS=$?

            if [ $EXIT_STATUS -ne 0 ] || grep -q "fatal error" "$METADAT_FILE"; then
                echo "Compilation failed with exit code: $EXIT_STATUS"
                [ -f "$AMX_O" ] && rm -rf "$AMX_O"
            fi

            _cache_compiler
            sleep 0
            cat "$METADAT_FILE"

            if [ -s "$AMX_O" ]; then
                echo
                echo "~ $AMX_O"
                if [ "$COMPILER_MODE" == "true" ]; then
                    BASH_TITLE="compilers"
                    bash_title "$SHUSERS:~/ $BASH_TITLE"
                elif [ "$COMPILER_MODE" == "false" ]; then
                    BASH_TITLE="compiler - running"
                    bash_title "$SHUSERS:~/ $BASH_TITLE"
                fi
                echo "total size : $(stat -c%s "$AMX_O") bytes"
                echo
            else
                if [ "$COMPILER_MODE" == "false" ]; then
                    bash_end ""
                fi
            fi
        fi
    done

    if [ "$SHFILE" == "false" ]; then
        echo -n "$(bash_coltext_r "..io not found!")"
        echo
        bash_end ""
    fi
    if [ "$COMPILER_MODE" == "true" ]; then
        bash_end ""
    elif [ "$COMPILER_MODE" == "false" ]; then
        ok_next
    fi
}

function _cache_compiler() {
    cache_compiler=".cache/compiler.log"
    _cache_compiler=".cache/.compiler.log"
    if [ -f "$_cache_compiler" ]; then
        rm -rf "$_cache_compiler"
    fi
    while IFS= read -r line; do
        echo "~" >> "$_cache_compiler"
        echo "$line" >> "$_cache_compiler"
    done < "$cache_compiler"
    mv "$_cache_compiler" "$cache_compiler" >/dev/null
}

function bash_check_dir() {
    local folder=$1
    if [ -d "$folder" ]; then
        echo
        echo "# $folder is .. Ok .."
        echo " [A subdirectory or file $folder already exists.]"
        echo "-"
        sleep 1
    else
        mkdir -p "$folder"
        echo "OK? '$BASH_DIR/$folder'...: [yes]"

        cat <<EOF > gamemodes/main.io.pwn
#include <a_samp>

main() {
    print("Hello, World!");
}
EOF
        sleep 1
    fi
}

function check2() {
    if grep -i "failed" server_log.txt >/dev/null; then
        start_true2
    else
        start_false2
    fi
}

function check3() {
    if grep -i "invalid" server_log.txt >/dev/null; then
        start_true3
    else
        start_false3
    fi
}

function start_true() {
    echo -n "$(bash_coltext_r "~")"
    echo "    ; \"error\"   .. Yes .. True"
    error_cache
}

function start_false() {
    echo -n "$(bash_coltext_y "~")"
    echo "    ; \"error\"   .. No .. False"
    check2
}

function start_true2() {
    echo -n "$(bash_coltext_r "~")"
    echo "    ; \"failed\"  .. Yes .. True"
    failed_cache
}

function start_false2() {
    echo -n "$(bash_coltext_y "~")"
    echo "    ; \"failed\"  .. No .. False"
    check3
}

function start_true3() {
    echo -n "$(bash_coltext_r "~")"
    echo "    ; \"invalid\" .. Yes .. True"
    invalid_cache
}

function start_false3() {
    echo -n "$(bash_coltext_y "~")"
    echo "    ; \"invalid\" .. No .. False"
    echo
    bash_end ""
}

function error_cache() {
    echo
    grep -i "error" server_log.txt
    echo
    check2
}

function failed_cache() {
    echo
    grep -i "failed" server_log.txt
    echo
    check3
}

function invalid_cache() {
    echo
    grep -i "invalid" server_log.txt
    echo
    bash_end ""
}

function ok_next() {
    echo -n "$(bash_coltext_y "Press any key to running.")"
    echo
    read -r -n 1 -s
    bash_servers
}

bash_typeof ""
